# Generated by Django 3.1.1 on 2020-10-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201024_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_likes',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
