# Generated by Django 3.1.1 on 2020-10-25 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tweet_likes_liked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet_likes',
            name='liked_user_id',
            field=models.ForeignKey(db_column='liked_user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='tweet_likes',
            name='tweet_id',
            field=models.ForeignKey(db_column='tweet_id', on_delete=django.db.models.deletion.CASCADE, to='user.tweet'),
        ),
    ]
