# Generated by Django 3.1.1 on 2020-10-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201025_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='parent_tweet_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
