# Generated by Django 3.1.1 on 2020-10-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20201025_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='parent_tweet_id',
            field=models.IntegerField(default=0),
        ),
    ]
