# Generated by Django 3.1.1 on 2020-10-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20201025_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='parent_tweet_id',
            field=models.IntegerField(null=True),
        ),
    ]
